# Generated by Django 3.2.12 on 2022-02-20 11:54

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220219_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RentAgreement',
            fields=[
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.apartment')),
                ('start_date', models.DateField(default=api.utils.get_current_date)),
                ('end_date', models.DateField(default=api.utils.get_date_in_30_days)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_agreements', to='api.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_agreements', to='api.person')),
            ],
        ),
    ]
