# Generated by Django 3.2.12 on 2022-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_rentagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
